var hierarchy =
[
    [ "robotoc::BackwardRiccatiRecursionFactorizer", "classrobotoc_1_1_backward_riccati_recursion_factorizer.html", null ],
    [ "robotoc::CoMRefBase", "classrobotoc_1_1_co_m_ref_base.html", [
      [ "robotoc::DiscreteTimeCoMRef", "classrobotoc_1_1_discrete_time_co_m_ref.html", null ],
      [ "robotoc::MPCPeriodicCoMRef", "classrobotoc_1_1_m_p_c_periodic_co_m_ref.html", null ],
      [ "robotoc::PeriodicCoMRef", "classrobotoc_1_1_periodic_co_m_ref.html", null ]
    ] ],
    [ "robotoc::ConfigurationSpaceRefBase", "classrobotoc_1_1_configuration_space_ref_base.html", [
      [ "robotoc::MPCPeriodicConfigurationRef", "classrobotoc_1_1_m_p_c_periodic_configuration_ref.html", null ]
    ] ],
    [ "robotoc::ConstraintComponentData", "classrobotoc_1_1_constraint_component_data.html", null ],
    [ "robotoc::Constraints", "classrobotoc_1_1_constraints.html", null ],
    [ "robotoc::ConstraintsData", "classrobotoc_1_1_constraints_data.html", null ],
    [ "robotoc::ContactDynamicsData", "classrobotoc_1_1_contact_dynamics_data.html", null ],
    [ "robotoc::ContactModelInfo", "structrobotoc_1_1_contact_model_info.html", null ],
    [ "robotoc::ContactPlannerBase", "classrobotoc_1_1_contact_planner_base.html", [
      [ "robotoc::BipedWalkFootStepPlanner", "classrobotoc_1_1_biped_walk_foot_step_planner.html", null ],
      [ "robotoc::CrawlFootStepPlanner", "classrobotoc_1_1_crawl_foot_step_planner.html", null ],
      [ "robotoc::FlyingTrotFootStepPlanner", "classrobotoc_1_1_flying_trot_foot_step_planner.html", null ],
      [ "robotoc::JumpFootStepPlanner", "classrobotoc_1_1_jump_foot_step_planner.html", null ],
      [ "robotoc::PaceFootStepPlanner", "classrobotoc_1_1_pace_foot_step_planner.html", null ],
      [ "robotoc::TrotFootStepPlanner", "classrobotoc_1_1_trot_foot_step_planner.html", null ]
    ] ],
    [ "robotoc::ContactSequence", "classrobotoc_1_1_contact_sequence.html", null ],
    [ "robotoc::ContactStatus", "classrobotoc_1_1_contact_status.html", null ],
    [ "robotoc::ControlPolicy", "structrobotoc_1_1_control_policy.html", null ],
    [ "robotoc::CostFunction", "classrobotoc_1_1_cost_function.html", null ],
    [ "robotoc::CostFunctionData", "structrobotoc_1_1_cost_function_data.html", null ],
    [ "robotoc::DerivativeChecker", "classrobotoc_1_1_derivative_checker.html", null ],
    [ "robotoc::DirectMultipleShooting", "classrobotoc_1_1_direct_multiple_shooting.html", null ],
    [ "robotoc::DiscreteEvent", "classrobotoc_1_1_discrete_event.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "robotoc::ConstraintComponentBase", "classrobotoc_1_1_constraint_component_base.html", [
        [ "robotoc::ContactWrenchCone", "classrobotoc_1_1_contact_wrench_cone.html", null ],
        [ "robotoc::FrictionCone", "classrobotoc_1_1_friction_cone.html", null ],
        [ "robotoc::JointAccelerationLowerLimit", "classrobotoc_1_1_joint_acceleration_lower_limit.html", null ],
        [ "robotoc::JointAccelerationUpperLimit", "classrobotoc_1_1_joint_acceleration_upper_limit.html", null ],
        [ "robotoc::JointPositionLowerLimit", "classrobotoc_1_1_joint_position_lower_limit.html", null ],
        [ "robotoc::JointPositionUpperLimit", "classrobotoc_1_1_joint_position_upper_limit.html", null ],
        [ "robotoc::JointTorquesLowerLimit", "classrobotoc_1_1_joint_torques_lower_limit.html", null ],
        [ "robotoc::JointTorquesUpperLimit", "classrobotoc_1_1_joint_torques_upper_limit.html", null ],
        [ "robotoc::JointVelocityLowerLimit", "classrobotoc_1_1_joint_velocity_lower_limit.html", null ],
        [ "robotoc::JointVelocityUpperLimit", "classrobotoc_1_1_joint_velocity_upper_limit.html", null ]
      ] ],
      [ "robotoc::CostFunctionComponentBase", "classrobotoc_1_1_cost_function_component_base.html", [
        [ "robotoc::CoMCost", "classrobotoc_1_1_co_m_cost.html", null ],
        [ "robotoc::ConfigurationSpaceCost", "classrobotoc_1_1_configuration_space_cost.html", null ],
        [ "robotoc::LocalContactForceCost", "classrobotoc_1_1_local_contact_force_cost.html", null ],
        [ "robotoc::TaskSpace3DCost", "classrobotoc_1_1_task_space3_d_cost.html", null ],
        [ "robotoc::TaskSpace6DCost", "classrobotoc_1_1_task_space6_d_cost.html", null ]
      ] ],
      [ "robotoc::ImpactConstraintComponentBase", "classrobotoc_1_1_impact_constraint_component_base.html", [
        [ "robotoc::ImpactFrictionCone", "classrobotoc_1_1_impact_friction_cone.html", null ],
        [ "robotoc::ImpactWrenchCone", "classrobotoc_1_1_impact_wrench_cone.html", null ]
      ] ],
      [ "robotoc::STOCostFunctionComponentBase", "classrobotoc_1_1_s_t_o_cost_function_component_base.html", null ]
    ] ],
    [ "robotoc::GridInfo", "structrobotoc_1_1_grid_info.html", null ],
    [ "robotoc::ImpactStage", "classrobotoc_1_1_impact_stage.html", null ],
    [ "robotoc::ImpactStatus", "classrobotoc_1_1_impact_status.html", null ],
    [ "robotoc::IntermediateStage", "classrobotoc_1_1_intermediate_stage.html", null ],
    [ "robotoc::LineSearch", "classrobotoc_1_1_line_search.html", null ],
    [ "robotoc::LineSearchFilter", "classrobotoc_1_1_line_search_filter.html", null ],
    [ "robotoc::LineSearchSettings", "structrobotoc_1_1_line_search_settings.html", null ],
    [ "robotoc::LQRPolicy", "classrobotoc_1_1_l_q_r_policy.html", null ],
    [ "robotoc::MovingWindowFilter< dim >", "classrobotoc_1_1_moving_window_filter.html", null ],
    [ "robotoc::MovingWindowFilter< 2 >", "classrobotoc_1_1_moving_window_filter.html", null ],
    [ "robotoc::MPCBipedWalk", "classrobotoc_1_1_m_p_c_biped_walk.html", null ],
    [ "robotoc::MPCCrawl", "classrobotoc_1_1_m_p_c_crawl.html", null ],
    [ "robotoc::MPCFlyingTrot", "classrobotoc_1_1_m_p_c_flying_trot.html", null ],
    [ "robotoc::MPCJump", "classrobotoc_1_1_m_p_c_jump.html", null ],
    [ "robotoc::MPCPace", "classrobotoc_1_1_m_p_c_pace.html", null ],
    [ "robotoc::MPCTrot", "classrobotoc_1_1_m_p_c_trot.html", null ],
    [ "robotoc::OCP", "structrobotoc_1_1_o_c_p.html", null ],
    [ "robotoc::OCPData", "structrobotoc_1_1_o_c_p_data.html", null ],
    [ "robotoc::OCPSolver", "classrobotoc_1_1_o_c_p_solver.html", null ],
    [ "robotoc::ParNMPCIntermediateStage", "classrobotoc_1_1_par_n_m_p_c_intermediate_stage.html", null ],
    [ "robotoc::ParNMPCTerminalStage", "classrobotoc_1_1_par_n_m_p_c_terminal_stage.html", null ],
    [ "robotoc::PerformanceIndex", "structrobotoc_1_1_performance_index.html", null ],
    [ "robotoc::PointContact", "classrobotoc_1_1_point_contact.html", null ],
    [ "robotoc::RaibertHeuristic", "classrobotoc_1_1_raibert_heuristic.html", null ],
    [ "robotoc::RiccatiFactorizer", "classrobotoc_1_1_riccati_factorizer.html", null ],
    [ "robotoc::RiccatiRecursion", "classrobotoc_1_1_riccati_recursion.html", null ],
    [ "robotoc::Robot", "classrobotoc_1_1_robot.html", null ],
    [ "robotoc::RobotModelInfo", "structrobotoc_1_1_robot_model_info.html", null ],
    [ "robotoc::RobotProperties", "structrobotoc_1_1_robot_properties.html", null ],
    [ "robotoc::SE3JacobianInverse", "classrobotoc_1_1_s_e3_jacobian_inverse.html", null ],
    [ "robotoc::SolutionInterpolator", "classrobotoc_1_1_solution_interpolator.html", null ],
    [ "robotoc::SolverOptions", "structrobotoc_1_1_solver_options.html", null ],
    [ "robotoc::SolverStatistics", "structrobotoc_1_1_solver_statistics.html", null ],
    [ "robotoc::SplitConstrainedRiccatiFactorization", "classrobotoc_1_1_split_constrained_riccati_factorization.html", null ],
    [ "robotoc::SplitDirection", "classrobotoc_1_1_split_direction.html", null ],
    [ "robotoc::SplitKKTMatrix", "classrobotoc_1_1_split_k_k_t_matrix.html", null ],
    [ "robotoc::SplitKKTResidual", "classrobotoc_1_1_split_k_k_t_residual.html", null ],
    [ "robotoc::SplitRiccatiFactorization", "classrobotoc_1_1_split_riccati_factorization.html", null ],
    [ "robotoc::SplitSolution", "classrobotoc_1_1_split_solution.html", null ],
    [ "robotoc::StateEquationData", "classrobotoc_1_1_state_equation_data.html", null ],
    [ "robotoc::STOConstraints", "classrobotoc_1_1_s_t_o_constraints.html", null ],
    [ "robotoc::STOCostFunction", "classrobotoc_1_1_s_t_o_cost_function.html", null ],
    [ "robotoc::STOPolicy", "classrobotoc_1_1_s_t_o_policy.html", null ],
    [ "robotoc::SurfaceContact", "classrobotoc_1_1_surface_contact.html", null ],
    [ "SwingFootRefBase", null, [
      [ "robotoc::TrotSwingFootRef", "classrobotoc_1_1_trot_swing_foot_ref.html", null ]
    ] ],
    [ "robotoc::SwitchingConstraintData", "classrobotoc_1_1_switching_constraint_data.html", null ],
    [ "robotoc::SwitchingTimeOptimization", "classrobotoc_1_1_switching_time_optimization.html", null ],
    [ "robotoc::TaskSpace3DRefBase", "classrobotoc_1_1_task_space3_d_ref_base.html", [
      [ "robotoc::DiscreteTimeSwingFootRef", "classrobotoc_1_1_discrete_time_swing_foot_ref.html", null ],
      [ "robotoc::MPCPeriodicSwingFootRef", "classrobotoc_1_1_m_p_c_periodic_swing_foot_ref.html", null ],
      [ "robotoc::PeriodicSwingFootRef", "classrobotoc_1_1_periodic_swing_foot_ref.html", null ]
    ] ],
    [ "robotoc::TaskSpace6DRefBase", "classrobotoc_1_1_task_space6_d_ref_base.html", null ],
    [ "robotoc::TerminalStage", "classrobotoc_1_1_terminal_stage.html", null ],
    [ "robotoc::TimeDiscretization", "classrobotoc_1_1_time_discretization.html", null ],
    [ "robotoc::Timer", "classrobotoc_1_1_timer.html", null ],
    [ "robotoc::UnconstrBackwardCorrection", "classrobotoc_1_1_unconstr_backward_correction.html", null ],
    [ "robotoc::UnconstrBackwardRiccatiRecursionFactorizer", "classrobotoc_1_1_unconstr_backward_riccati_recursion_factorizer.html", null ],
    [ "robotoc::UnconstrDirectMultipleShooting", "classrobotoc_1_1_unconstr_direct_multiple_shooting.html", null ],
    [ "robotoc::UnconstrDynamics", "classrobotoc_1_1_unconstr_dynamics.html", null ],
    [ "robotoc::UnconstrIntermediateStage", "classrobotoc_1_1_unconstr_intermediate_stage.html", null ],
    [ "robotoc::UnconstrKKTMatrixInverter", "classrobotoc_1_1_unconstr_k_k_t_matrix_inverter.html", null ],
    [ "robotoc::UnconstrLineSearch", "classrobotoc_1_1_unconstr_line_search.html", null ],
    [ "robotoc::UnconstrOCPData", "structrobotoc_1_1_unconstr_o_c_p_data.html", null ],
    [ "robotoc::UnconstrOCPSolver", "classrobotoc_1_1_unconstr_o_c_p_solver.html", null ],
    [ "robotoc::UnconstrParNMPCSolver", "classrobotoc_1_1_unconstr_par_n_m_p_c_solver.html", null ],
    [ "robotoc::UnconstrRiccatiFactorizer", "classrobotoc_1_1_unconstr_riccati_factorizer.html", null ],
    [ "robotoc::UnconstrRiccatiRecursion", "classrobotoc_1_1_unconstr_riccati_recursion.html", null ],
    [ "robotoc::UnconstrSplitBackwardCorrection", "classrobotoc_1_1_unconstr_split_backward_correction.html", null ],
    [ "robotoc::UnconstrTerminalStage", "classrobotoc_1_1_unconstr_terminal_stage.html", null ]
];